import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import {AppDataProvider} from "@/providers/AppDataProvider";
import {AuthProvider} from "@/providers/AuthProvider";
import AppShell from "@/components/layout/AppShell";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <html lang="fr" data-theme="winter" suppressHydrationWarning>
            <head>
                <script
                    dangerouslySetInnerHTML={{
                        __html: `
                (function(){
                  try {
                    var t = localStorage.getItem('theme');
                    if (t) document.documentElement.setAttribute('data-theme', t);
                  } catch(e) {}
                })();`,
                    }}
                />
            </head>
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-svh`}>
                <AuthProvider>
                    <AppDataProvider>
                        <AppShell>
                            {children}
                        </AppShell>
                    </AppDataProvider>
                </AuthProvider>
            </body>
        </html>
    );
}
