import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout/Navbar";
import Breadcrumbs from "@/components/layout/Breadcrumbs";
import Footer from "@/components/layout/Footer";
import Sidebar from "@/components/layout/Sidebar";
import {AppDataProvider} from "@/providers/AppDataProvider";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    const drawerId = "my-drawer-2";

    return (
        <html lang="fr" data-theme="winter" suppressHydrationWarning>
            <head>
                <script
                    dangerouslySetInnerHTML={{
                        __html: `
                (function(){
                  try {
                    var t = localStorage.getItem('theme');
                    if (t) document.documentElement.setAttribute('data-theme', t);
                  } catch(e) {}
                })();`,
                    }}
                />
            </head>
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-svh`}>
                <AppDataProvider>
                    <div className="drawer lg:drawer-open min-h-svh">
                        <div className="drawer-content flex flex-col min-h-svh">
                            <Navbar drawerId={drawerId} />

                            {/* <- important */}
                            <main className="flex-1 p-4 md:p-6 lg:p-8">
                                <div className="mx-auto space-y-4">
                                    <Breadcrumbs />
                                    {children}
                                </div>
                            </main>

                            <Footer />  {/* pas de fixed ici */}
                        </div>
                        <Sidebar drawerId={drawerId} />
                    </div>
                </AppDataProvider>
            </body>
        </html>
    );
}
